---
title: "Tables of abundance and basal area"
subtitle: BCI, Sherman and Cocoli
author: "Mauro Lepore"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: '3'
    theme: united
    keep_md: true
---

```{r setup, include=FALSE}
# This chunk named setup will run before any other code (https://goo.gl/BeM2Uu)
set.seed(1014)
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  comment = "#>",
  collapse = TRUE,
  cache = FALSE,
  # Figures (http://r4ds.had.co.nz/)
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,
  fig.show = "hold"
)
```

### Setup

```{r packages, eval=TRUE, message=FALSE, warning=FALSE} 
library(tidyverse)
library(fgeo)
```

### Implementation-details

[Notes on code development](https://github.com/forestgeo/fgeo.abundance/blob/master/inst/issues/59_abund_tables/count_samplings.md#creating-tables-of-abundance-and-basal-area).

```{r}
create_table <- function(vft, plotname, table_byyr, ...) {
  vft_plot <- pick_plotname(vft, plotname)
  table_byyr(vft_plot, ...)
}

# Standardize basal area by total plot-hectares.
standardize_ba <- function(ba, denominator) {
  years <- setdiff(names(ba), c("species", "Family"))
  in_he <- convert_unit_at(ba, .at = years, from = "mm2", to = "m2")
  standardize_at(in_he, years, denominator)
}

create_all_tables <- function(vft, plotname, denominator) {
  tree_abund <- create_table(vft, plotname, abundance_byyr, dbh >= 100)
  sap_tree_abund <- create_table(vft, plotname, abundance_byyr, dbh >= 10)
  tree_basal <- create_table(vft, plotname, basal_area_byyr, dbh >= 100) %>% 
    standardize_ba(denominator)
  sap_tree_basal <- create_table(vft, plotname, basal_area_byyr, dbh >= 10) %>% 
    standardize_ba(denominator)
  
  list(
    tree_abundance = tree_abund,
    tree_basal_area = tree_basal,
    sapling_tree_abundance = sap_tree_abund,
    sapling_tree_basal_area = sap_tree_basal
  )
}

write_all_tables <- function(vft, plotname, dir, denominator) {
  tables <- create_all_tables(vft, plotname, denominator)
  fgeo.tool::dfs_to_csv(tables, dir, prefix = paste0(plotname, "_"))
}
```

### Read ViewFullTables

```{r data, message=FALSE} 
# BCI
path_bci <- here::here("inst/issues/59_abund_tables/vft_bci.csv")
vft_bci <- readr::read_csv(path_bci)

# Sherman and Cocoli
path_sc <- here::here("inst/issues/59_abund_tables/vft_sc.csv")
vft_sc <- readr::read_csv(path_sc)
```

### Create and write tables of abundance and basal area by year

```{r, message=FALSE, warning=FALSE}
dir <- here::here("inst/issues/59_abund_tables/out")
bci <- vft_bci
# bci <- sample_n(vft_bci, 10)
write_all_tables(bci, plotname = "bci", dir, denominator = 50)

sc <- vft_sc
# sc <- sample_n(vft_sc, 10)
write_all_tables(sc, plotname = "sherman", dir, 5.96)
write_all_tables(sc, plotname = "cocoli", dir, denominator = 4)
```

### Visualize output

```{r, message=FALSE, eval=TRUE}
folder <- here::here("inst/issues/59_abund_tables/out")
dfs <- csv_to_dfs(folder)
str(dfs, give.attr = FALSE)
```

### Compare with previous tables

Compare with:

* Saplings and trees: https://forestgeo.si.edu/bci-abundance-all-tree-species-50-ha-plot-1982-2005-saplings-and-trees

* Trees: https://forestgeo.si.edu/bci-abundance-all-tree-species-50-ha-plot-1982-2005-trees

Also:

```{r, message=FALSE, eval=TRUE}
folder <- here::here("inst/issues/59_abund_tables/condit_et_al")
paths <- fs::path(folder, dir(folder))
dfs <- map(paths, read_delim, delim = "\t")
set_names(dfs, basename(paths))
```

