---
title: "Contribute"
subtitle: "Guidelines for developing forestr"
author: "Mauro Lepore"
date: "2017-08-16"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 6
vignette: >
  %\VignetteIndexEntry{Contribute}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo = FALSE, message=FALSE, warning=FALSE}
# hadley's settings
set.seed(1014)
options(digits = 3)

knitr::opts_chunk$set(
  echo = TRUE,  # {mine}
  comment = "#>",
  collapse = TRUE,
  # cache = TRUE,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  fig.asp = 0.618,  # 1 / phi
  fig.show = "hold"
)

options(dplyr.print_min = 6, dplyr.print_max = 6)
```

# Organization of Functions

## Naming Files and Organizing Functions.

Functions are gropued into files named after the functions' topic. If appropriate, topic (and file) names correspond to the names of the folders and files in the original __CTFS R Package__ by Richard Condit. In each file:

* Place first the functions that appear in the functions' index: functions tagged with `@export` but not with `@keywords internal`. 

* Then, place exported functions that do not appear in the function's index: functions tagged not only with `@export` but also with `@keywords internal`. 

* Finally, place functions that are not exported; commonly, these are functions that other functions use but are not intended for users to use directly.

This organization follows a Lead-Development structure. Similarly to writing a paper, this structure makes the code more readable because readers get first an overview at the level of intention, then followed by the details. In any file, as readers move from top to bottom, the level of abstraction lowers and the level of detail highers. In practice, this means you should place primary functions before the other functions on which the primary functions depend. 

## Placing Functions that Validate Inputs to Other Functions

Functions that validate the inputs passed to other functions are named `validate_FUNCTION()` and are all placed at the bottom of the same file than the functions they validate, in a separate section created with (Control + shift + R):

```
# Validate ----------------------------------------------------------------

```
In each file, match the order between the `FUNCTION()`s and the `validate_FUNCTION()`s to make it easy to navigate the function's outline (Shift + Control + O).

## Naming Tests

Place tests into the directory `tests/testthat/` in files named `test-FUNCTION.R`. To do this easyily, run `testthat::use_test("FUNCTION")`.

