#' Remove files from base directory.
#' 
#' Useful to clean .pdf and .png files generated by tests, vignettes, and
#' interactive use.
#' 
#' @param base The base of a directory, e.g. "./vignettes/".
#' @param file A file name, e.g. myplot.pdf.
#' 
#' @examples
#' # remove pdf files from working directory
#' # rm_files("./", "pdf$")
#' 
#' @noRd
rm_files <- function(base, file = "pdf$") {
  files <- dir(base)
  file_nm <- files[grepl(file, files)]
  file.remove(paste0(base, file_nm))
}

