#' Remove pdf files from base directory. 
#' 
#' Useful to clean .pdf files generated by tests, vignettes, and interactive
#' use.
#' 
#' @noRd
#' # bases <- c(
#' #  "./",
#' #  "./vignettes",
#' #  "./tests/testthat/"
#' # )
#' # lapply(bases, rm_pdf)
rm_pdf <- function(base) {
  files <- files(base)
  pdfs <- files[grepl("pdf$", files)]
  file.remove(paste0(base, pdfs))
}

